export const SCHOOLTYPES = [
    "Gymnasium",
    "Gesamtschule",
    "Realschule",
    "Schule mit mehreren Bildungsgängen",
    "Hauptschule",
    "Berufliche Schule",
    "Grundschule",
    "Förderschule",
    "Erwachsenenbildung",
    "Kindergarten",
];

export const CLASSES = [
    "1./2. Schuljahr",
    "3./4. Schuljahr",
    "5./6. Schuljahr",
    "9./10. Schuljahr",
    "Sekundarstufe II",
    "Lebenslanges Lernen",
];

export const SUBJECTS = [
    "Arbeitslehre",
    "Astronomie",
    "Berufsvorbereitung",
    "Biologie",
    "Chemie",
    "Deutsch",
    "Deutsch als Fremdsprache (DaF)",
    "Deutsch als Zweitsprache (DaZ)",
    "Englisch",
    "Erdkunde/Geografie",
    "Ethik",
    "Evangelische Religionslehre",
    "Französisch",
    "Gemeinschaftskunde",
    "Geschichte",
    "Gesellschaftslehre",
    "Informatik",
    "Katholische Religionslehre",
    "Kunst",
    "Latein",
    "Mathematik",
    "Musik",
    "Naturwissenschaften",
    "Physik",
    "Politik",
    "Praktische Philosophie",
    "Pädagogik",
    "Russisch",
    "Sachunterricht",
    "Sozialwissenschaften",
    "Spanisch",
    "Sprachen",
    "Technik",
    "Wirtschaft",
    "fachunabhängige Verwendung",
];

export const USECASE = [
    "Organisation/Administration",
    "Infrastruktur",
    "Nachhilfe",
    "Selbstlernen",
    "Unterrichtsvorbereitung",
    "Unterrichtsdurchführung",
    "Fortbildung für Lehrer*innen",
];
